$ErrorActionPreference = "Stop"

$root = Split-Path -Parent $MyInvocation.MyCommand.Path
$detailsRoot = Join-Path $root "assets\new-details"
$outputFile = Join-Path $root "extra-projects.js"

function ConvertTo-JsString {
  param([string]$Value)
  if ($null -eq $Value) { return '""' }
  $escaped = $Value.Replace("\", "\\").Replace('"', '\"').Replace("`r", "").Replace("`n", "\n")
  return '"' + $escaped + '"'
}

if (-not (Test-Path $detailsRoot)) {
  New-Item -ItemType Directory -Path $detailsRoot | Out-Null
}

$projects = @()
$projectFolders = Get-ChildItem -LiteralPath $detailsRoot -Directory | Sort-Object Name
$nextId = 9000

foreach ($folder in $projectFolders) {
  $images = Get-ChildItem -LiteralPath $folder.FullName -File |
    Where-Object { $_.Extension.ToLower() -in @(".jpg", ".jpeg", ".png", ".webp") } |
    Sort-Object Name

  if ($images.Count -eq 0) { continue }

  $title = $folder.Name
  $cover = "assets/new-details/$title/" + $images[0].Name
  $imagePaths = @()
  foreach ($image in $images) {
    $imagePaths += "assets/new-details/$title/" + $image.Name
  }

  $descriptionFile = Join-Path $folder.FullName "description.txt"
  if (Test-Path $descriptionFile) {
    $description = (Get-Content -Raw -Encoding UTF8 -LiteralPath $descriptionFile).Trim()
  } else {
    $description = "$title portfolio detail page."
  }

  $updatedAt = Get-Date -Format "yyyy-MM"
  $historyLimit = 12
  $updateMonths = @($updatedAt)
  $metaFile = Join-Path $folder.FullName "meta.txt"

  if (Test-Path $metaFile) {
    $metaLines = Get-Content -Encoding UTF8 -LiteralPath $metaFile
    foreach ($line in $metaLines) {
      $clean = $line.Trim()
      if ($clean -eq "" -or $clean.StartsWith("#")) { continue }

      if ($clean -match "^更新时间\s*=\s*(.+)$") {
        $updatedAt = $Matches[1].Trim()
        $updateMonths = @($updatedAt)
      } elseif ($clean -match "^显示记录\s*=\s*(\d+)$") {
        $historyLimit = [int]$Matches[1]
      } elseif ($clean -match "^修改记录\s*=\s*(.+)$") {
        $updateMonths = $Matches[1].Split(",") | ForEach-Object { $_.Trim() } | Where-Object { $_ -ne "" }
      }
    }
  }

  $imageList = ($imagePaths | ForEach-Object { ConvertTo-JsString $_ }) -join ", "
  $monthList = ($updateMonths | ForEach-Object { ConvertTo-JsString $_ }) -join ", "
  $projects += @"
  {
    id: $nextId,
    type: "image",
    title: $(ConvertTo-JsString $title),
    mainCategory: "2d",
    subCategory: "detail",
    coverImage: $(ConvertTo-JsString $cover),
    detailImages: [$imageList],
    tags: ["Detail", "New Work", "E-commerce"],
    description: $(ConvertTo-JsString $description),
    updatedAt: $(ConvertTo-JsString $updatedAt),
    historyLimit: $historyLimit,
    updateMonths: [$monthList]
  }
"@
  $nextId++
}

$content = @"
// Generated by update-projects.ps1.
// Do not edit manually. Add folders under assets/new-details and run the script.
window.extraPortfolioProjects = [
$($projects -join ",`n")
];
"@

Set-Content -LiteralPath $outputFile -Value $content -Encoding UTF8
Write-Host "Updated extra-projects.js. Added $($projects.Count) extra projects." -ForegroundColor Green
Write-Host "Next commands:" -ForegroundColor Cyan
Write-Host "git add ."
Write-Host "git commit -m `"Update portfolio works`""
Write-Host "git push -u origin main"
